"""Report service - PDF generation for weekly reports."""

import io
from app.models.ai_insights import WeeklyReport


async def generate_report_pdf(report: WeeklyReport) -> io.BytesIO:
    """Generate a PDF report from weekly report data."""
    from jinja2 import Template

    html_template = Template("""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #1a1a1a; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #f97316; padding-bottom: 20px; }
            .header h1 { color: #f97316; margin: 0; font-size: 28px; }
            .header p { color: #666; margin-top: 5px; }
            .scores { display: flex; justify-content: space-around; margin: 30px 0; }
            .score-card { text-align: center; padding: 20px; border-radius: 12px; background: #f8f9fa; }
            .score-card .value { font-size: 36px; font-weight: bold; color: #f97316; }
            .score-card .label { color: #666; font-size: 14px; margin-top: 5px; }
            .section { margin: 25px 0; }
            .section h2 { color: #333; border-bottom: 1px solid #eee; padding-bottom: 8px; }
            .action-item { padding: 10px; margin: 8px 0; background: #fff7ed; border-left: 4px solid #f97316; border-radius: 4px; }
            .risk-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-weight: bold; font-size: 12px; }
            .risk-low { background: #d1fae5; color: #065f46; }
            .risk-medium { background: #fef3c7; color: #92400e; }
            .risk-high { background: #fee2e2; color: #991b1b; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎯 PocketBuddy Weekly Report</h1>
            <p>{{ week_start }} — {{ week_end }}</p>
        </div>

        <div class="scores">
            <div class="score-card">
                <div class="value">{{ financial_score }}</div>
                <div class="label">Financial Score</div>
            </div>
            <div class="score-card">
                <div class="value">{{ wellness_score }}</div>
                <div class="label">Wellness Score</div>
            </div>
            <div class="score-card">
                <div class="value risk-badge risk-{{ burnout_risk }}">{{ burnout_risk | upper }}</div>
                <div class="label">Burnout Risk</div>
            </div>
        </div>

        <div class="section">
            <h2>💰 Financial Summary</h2>
            <p>{{ financial_summary }}</p>
            {% if total_spent %}<p><strong>Total Spent:</strong> ₹{{ total_spent }}</p>{% endif %}
        </div>

        <div class="section">
            <h2>🧘 Wellness Summary</h2>
            <p>{{ wellness_summary }}</p>
        </div>

        <div class="section">
            <h2>📋 Action Plan</h2>
            {% for item in action_plan %}
            <div class="action-item">
                <strong>{{ item.get('category', 'general') | title }}:</strong> {{ item.get('action', item) }}
            </div>
            {% endfor %}
        </div>

        <div style="text-align: center; margin-top: 40px; color: #999; font-size: 12px;">
            Generated by PocketBuddy AI • Your Student Life Coach
        </div>
    </body>
    </html>
    """)

    html_content = html_template.render(
        week_start=str(report.week_start),
        week_end=str(report.week_end),
        financial_score=int(report.financial_score),
        wellness_score=int(report.wellness_score),
        burnout_risk=report.burnout_risk,
        financial_summary=report.financial_summary,
        wellness_summary=report.wellness_summary,
        total_spent=report.total_spent,
        action_plan=report.action_plan or [],
    )

    # Generate PDF using weasyprint
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html_content).write_pdf()
        return io.BytesIO(pdf_bytes)
    except ImportError:
        # Fallback: return HTML as bytes if weasyprint not available
        return io.BytesIO(html_content.encode("utf-8"))
